namespace ProjectEuler.Rud
{
    class Problem2 : Problem
    {
        public Problem2()
        {
            description =
@"Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.";
        }

        protected override void Solve()
        {
            int sum = 0;

            int x = 1;
            int x1 = 1;
            int x2 = 0;

            while (x <= 4000000)
            {
                x = x1 + x2;
                x2 = x1;
                x1 = x;
                if (x % 2 == 0)
                {
                    sum += x;
                }
            }

            answer = sum.ToString();
        }
    }
}
